#!/usr/bin/env bash

export FZF_DEFAULT_OPTS=" \
--color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8 \
--color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc \
--color=marker:#b4befe,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8 \
--multi \
--layout=reverse \
--border \
--preview='lta2 --ignore-glob node_modules' \
--margin=1 \
--no-scrollbar \
--ansi \
--header='Choose a folder to open in a new tmux session' \
--header-first \
--preview-label='File Preview' \
--preview-window='right:30%:wrap' \
--tmux=80%"

if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(find ~/ ~/software-development ~/software-development/work ~/.config ~/.local -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

if ! tmux has-session -t=$selected_name 2>/dev/null; then
  tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
